# Generated by Django 6.0 on 2025-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0002_carritodecompras_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
