# Generated by Django 6.0 on 2025-12-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0003_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorpresas_kawai.combo'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorpresas_kawai.producto'),
        ),
    ]
