# Generated by Django 6.0 on 2025-12-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0004_itemcarrito_combo_alter_itemcarrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='nombre',
            field=models.CharField(default='Combo', max_length=255, null=True),
        ),
    ]
