# Generated by Django 6.1 on 2026-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0007_combo_descripcion_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='combos', through='sorpresas_kawai.CombosProductos', to='sorpresas_kawai.producto'),
        ),
    ]
