# Generated by Django 6.1 on 2026-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0008_combo_imagen_producto_imagen_alter_combo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.FloatField(default=0.0),
        ),
    ]
