# Generated by Django 6.1 on 2026-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorpresas_kawai', '0009_producto_descuento_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa_envio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa de Envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Guía'),
        ),
    ]
